apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: go-test22222
  namespace: openshift-gitops 
  finalizers: ["resources-finalizer.argocd.argoproj.io"] 
spec:
  project: default
  source:
    path: ./components/go-test22222/overlays/development
    repoURL: https://github.com/stephanie-cy/go-test22222-gitops
    targetRevision: main
  destination:
    namespace: go-test-tekton
    server: https://kubernetes.default.svc
  syncPolicy:
    managedNamespaceMetadata:
      labels: 
        argocd.argoproj.io/managed-by: openshift-gitops
    automated: 
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
